name: Test Terraform Module

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - README.md
      - CHANGELOG.md

jobs:
  tf-apply:
    name: Test terraform-honeycombio-opentelemetry-starter-pack
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tests
    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2

      - name: Set Honeycomb API Key environment variable
        run: echo "HONEYCOMB_API_KEY=${{ secrets.HONEYCOMB_API_KEY }}" >> $GITHUB_ENV

      - name: Create unique Dataset name for required columns dataset name
        run: echo "DSETNAME=$(date +%s)" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve -no-color -var "required_columns_dataset_name=${{ env.DSETNAME }}"

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -no-color -var "required_columns_dataset_name=${{ env.DSETNAME }}"
